spring:
  application:
    name: DTSCM2

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}


  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      jakarta.persistence.validation.mode: none

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: password